### ISSUE TITLE
style: add Unibeautify linting

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#13]
## Add Unibeautify Linting 

Being able to have formatted code that is aligned with the style guide is extremely important, not just for learning best practices but for the future of this project.

- [ ] Please add a `.unibeautifyrc.json` file with a linting configuration to match the languages used within this repository. 
- [ ] Please correct the current files to match the linting configurations (this should be in the details after you commit the first task^

**Comment by madiedgar** [comment]
https://medium.com/@jtomaszewski/keep-your-code-clean-forever-65c71f7f2df

https://medium.com/productivity-freak/my-atom-editor-setup-for-js-react-9726cd69ad20

**Comment by underscoreanuj** [comment]
I would like to work on this
