### ISSUE TITLE
Create confirmation on email subscription

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#16]
When a user enters their email, they should expect some sort of visual confirmation that their information was entered and received on the site.

**Comment by Aakash1822** [comment]
Please explain to me further about this issues and which file have require changes @madiedgar . I interested to work on this problem

**Comment by madiedgar** [comment]
This issue should be in the `legesher-pride` repo, @Aakash1822 if you're still interested it would entail utilizing Mailchimp and creating a confirmation email from their online design gui.
