### ISSUE TITLE
feat: add "Language: Ruby" to label gemfile

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#21]
## Language: Ruby

For our projects, we run a script that adds / updates all of the project labels. For hacktoberfest, we'd love to add a couple more to the mix so that we're consistent.

- `Language: Ruby`

This issue should have the color #F48370 associated with the label for a language. We also keep track of the labels within the documentation, so please add the labels to the markdown file.

**Comment by madiedgar** [comment]
Thanks Joel for tackling this! I changed the status from Available to Review Needed for the reasons described in the pull request. Great job! 🎉

**Comment by joelibaceta** [comment]
@madiedgar thanks 👍  happy coding!
