### ISSUE TITLE
docs: update README with new project list

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#28]
## Update README with new project list

Yay for updated documentation! We added a new repository just for non-programmers and thus need to update our repositories project list with the new information! 🎉 

The [Legesher Projects](https://github.com/legesher/legesher-docs#legesher-projects) section of the README needs to be updated in the following ways:

- [ ] Add the `legesher-pride` repository as a row in the table
  - [ ] Follow the table conventions introduced by the other row items
  - [ ] Add the description: `a non-programmer's dream to contributing to open source by sharing what they know and learning what's new`

**Comment by rajnish4unow** [comment]
can i take this up?

**Comment by madiedgar** [comment]
Absolutely! I'll assign you @rajnish4unow 😄
