### ISSUE TITLE
Add Github CLI Tutorial to Docs

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#35]
## Documentation: Add GitHub CLI Tutorial

This is SUCH an important issue as it helps our community grow and allow the hurdles to contribute to lower. Here's the basic idea:

>Create a comprehensive tutorial to help beginners navigate and contribute to the Legesher project using the CLI. 

Using the [toolbox document](https://github.com/legesher/legesher-docs/blob/master/guide/contributor/contributor-toolbox.md) as reference (also seen on the [documentation site](https://legesher.readme.io/docs/lets-get-it-started)) create a step by step walk through tutorial of the CLI tool for GitHub. 

Begin with installation instructions with pictures and take them along the journey to fork a Legesher repository to their account & local machine all using the CLI.

**Comment by jayeshmann** [comment]
Can I take this too?

**Comment by madiedgar** [comment]
Absolutely! 🎉
