### ISSUE TITLE
Add GitHub Desktop GUI Tutorial 

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#36]
## Documentation: Add GitHub Desktop GUI Tutorial

This is SUCH an important issue as it helps our community grow and allow the hurdles to contribute to lower. Here's the basic idea:

>Create a comprehensive tutorial to help beginners, namely _non-programmers_, navigate and contribute to the Legesher project using the GitHub Desktop GUI. 

Using the [toolbox document](https://github.com/legesher/legesher-docs/blob/master/guide/contributor/contributor-toolbox.md) as reference (also seen on the [documentation site](https://legesher.readme.io/docs/lets-get-it-started)) create a step by step walk through tutorial of GitHub Desktop GUI. 

Begin with installation instructions with pictures and take them along the journey to fork a Legesher repository to their account & local machine all using GitHub Desktop.

**Comment by jayeshmann** [comment]
I would like to make this tutorial.

**Comment by madiedgar** [comment]
Awesome @jayeshmann 👏 I'll assign you to this issue and reach out if you have any questions! Excited for this 😄

**Comment by jayeshmann** [comment]
Where can I reach out to you?

**Comment by jayeshmann** [comment]
Started working on this.

**Comment by madiedgar** [comment]
Best way would probably be through this thread, but if chat is more your style I'll hop on [discord](https://discord.gg/SqKBXuH)
