### ISSUE TITLE
Add Full Dialect List to Github Labels

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#37]
## Add Full Dialect List to GitHub Labels
We're adding new dialect translations incredibly fast, so having all of the dialect labels created and ready to go would be 👌! 

To complete this issue:
- [ ] Reference the [dialect list in `legesher-translations`](https://github.com/legesher/legesher-translations/blob/master/locale/dialect-list.yml)
- [ ] Navigate to [`guide/legesher/labels/legesher-issue-labels.rb`](https://github.com/legesher/legesher-docs/blob/master/guide/legesher/labels/legesher-issue-labels.rb)
- [ ] Add dialects in the **default_labels** in the form `"Dialect: Polish" => "CD5A86",` using the English language name.

**Comment by jgtiu** [comment]
I'd like to work on this!
