### ISSUE TITLE
Add Custom Label in Label Gem

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#41]
## Add New Custom Label to Gemfile

>:tada: FIRST TIMERS ONLY

We are adding a custom label to recognize the people who are contributing to the project by sharing the impact in other ways. 

**To complete this issue**:
- [ ] In the file `/guide/legesher/labels/legesher-issue-labels.rb`, please add this new custom label ✨ to the `all_contributors_labels` object (in alphabetical order please). 
```
  "💌 Opportunity: Marketing" => ["66CCFF", "People who help in marketing the repo/project"],
```
- [ ] Update the `/guide/legesher/roadmap.md` to include the new opportunity! 

Happy to help guide you along the way! Just reach out! 😄

**Comment by Mark-C-Hall** [comment]
Hello,
I would like to try this out!

**Comment by madiedgar** [comment]
Awesome!! I'll assign you to it @Mark-C-Hall!
