### ISSUE TITLE
Add Full Programming Language List to GitHub Labels

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#44]
## Add Full Programming Language List to GitHub Labels
We're adding new dialect translations incredibly fast, so having all of the programming language labels created and ready to go would be 👌! 

To complete this issue:
- [ ] Reference the [programming language list in `legesher-translations`](https://github.com/legesher/legesher-translations/blob/master/config/programming-languages.json)
- [ ] Navigate to [`guide/legesher/labels/legesher-issue-labels.rb`](https://github.com/legesher/legesher-docs/blob/master/guide/legesher/labels/legesher-issue-labels.rb)
- [ ] Add dialects in the **default_labels** in the form `"Language: Javascript" => "F48370",` using the programming language name. 
- [ ] Update the `roadmap.md` file in `legesher-docs/guide/legesher/` with the full list of programming languages.

**Comment by ewelinasobora** [comment]
I'm on it.

**Comment by madiedgar** [comment]
Amazing @ewelinasobora, I'll assign you to it 😄

**Comment by MHalseyPerry** [comment]
Sorry , forgot to claim. Have sent PR

**Comment by madiedgar** [comment]
No worries @MHalseyPerry, thanks for your contribution! @ewelinasobora do you mind doing #45?
