### ISSUE TITLE
Add Dialect List to Roadmap

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-docs#45]
## Add the full Dialect list to the documentation found in `legesher-docs/guide/legesher/roadmap.md`

Use the full dialect list found in [`legesher-issue-labels.rb`](https://github.com/legesher/legesher-docs/blob/master/guide/legesher/labels/legesher-issue-labels.rb) to write up the documentation.

**Comment by ewelinasobora** [comment]
I'd like to work on it :)

**Comment by madiedgar** [comment]
Awesome @ewelinasobora 🎉

**Comment by tawhk** [comment]
I have finished the Dialect list and I'm ready to PR.. do you want the list to be sorted alphabetically?

**Comment by madiedgar** [comment]
Thank you @tawhk! I'll look at it now!

@ewelinasobora do you think you could add the programming languages to this same `roadmap.md` file? I would create a new issue, but I want you to get this one 😉

**Comment by ewelinasobora** [comment]
> Thank you @tawhk! I'll look at it now!
> 
> @ewelinasobora do you think you could add the programming languages to this same `roadmap.md` file? I would create a new issue, but I want you to get this one 😉

@madiedgar thanks!  Sure I will add the programming languages to roadmap.md :)
