### ISSUE TITLE
Incorrect README displayed

### ISSUE THREAD

**Issue by onFilm** [legesher/legesher-docs#89]
**Describe the bug**
Repo README is overwritten by .github/README.md, Hence we ares seeing ".github" as content instead of actual README content.

**To Reproduce**
1. Go to the legesher-docs
2. See the content of README.md below the files section

**Expected behavior**
Actual README

**Screenshots**
 
![image](https://user-images.githubusercontent.com/26830666/127285967-04fefc09-4883-4bb8-8180-dab5858bbb53.png)

 **Possible Solution**
Delete README.md from .github directory

**Comment by AsianCat54x** [comment]
Can I work kn this issue?
